name: Build release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: plugin
          ref: ${{ github.ref }}

      - name: Checkout VC6 build tools
        uses: actions/checkout@v6
        with:
          repository: FLHDE/VC6-SP6-Enterprise
          path: VC6

      - name: Add VC6 build tools to path
        run: .\VC6\VC98\Bin\VCVARS32.BAT

      - name: Build plugin
        run: nmake /nologo

      - name: Upload release build as artifact
        uses: actions/upload-artifact@v7
        with:
          name: Release build
          path: |
            plugin/*.dll
